{{- if .Values.backend.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rainstone.backend.fullname" . }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rainstone.backend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "rainstone.backend.fullname" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 2
          livenessProbe:
            tcpSocket:
              port: http
{{- end }}
---
