{{- $basePath := (trimSuffix "/" (.Values.frontend.basePath | default "/")) | default "/" -}}
{{- $apiSubPath := printf "%s/api" (trimSuffix "/" $basePath) | replace "//" "/" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rainstone.frontend.fullname" . }}-config
data:
  config.js: |
    window.APP_CONFIG = {
      API_SUBPATH: '{{ $apiSubPath }}',
      BASE_URL: '{{ $basePath }}',
    };
