{{- if .Values.frontend.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rainstone.frontend.fullname" . }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rainstone.frontend.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "rainstone.frontend.fullname" . }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          volumeMounts:
            - name: config
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: config
          configMap:
            name: ui-config
        - name: nginx-config
          configMap:
            name: {{ include "rainstone.frontend.fullname" . }}-nginx-conf
{{- end }}
---
